global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['172.16.20.7:9100']
        labels:
          instance: db1

  - job_name: mysql
    static_configs:
      - targets: ['172.16.20.7:9104']
        labels:
          instance: db1
